serviceAccount: "projects/${PROJECT_ID}/serviceAccounts/sa-cloudbuild-dev@${PROJECT_ID}.iam.gserviceaccount.com"

options:
  logging: CLOUD_LOGGING_ONLY
  dynamic_substitutions: true

substitutions:
  _REGION: europe-west1
  _REPOSITORY: housemaster
  _SERVICE_NAME: next-web
  _IMAGE: ${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/web

steps:
  - name: "gcr.io/cloud-builders/docker"
    id: "build-image"
    args:
      - build
      - --tag
      - "${_IMAGE}:${SHORT_SHA}"
      - --tag
      - "${_IMAGE}:latest"
      - --cache-from
      - "${_IMAGE}:latest"
      - --build-arg
      - "BUILDKIT_INLINE_CACHE=1"
      - .
    env:
      - "DOCKER_BUILDKIT=1"

  - name: "gcr.io/cloud-builders/docker"
    id: "push-image"
    args:
      - push
      - "--all-tags"
      - "${_IMAGE}"

  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    id: "deploy-cloud-run"
    entrypoint: gcloud
    args:
      - run
      - deploy
      - "${_SERVICE_NAME}"
      - --image
      - "${_IMAGE}:${SHORT_SHA}"
      - --region
      - "${_REGION}"
      - --project
      - "${PROJECT_ID}"
      - --service-account
      - "sa-web-dev@${PROJECT_ID}.iam.gserviceaccount.com"
      - --quiet

images:
  - "${_IMAGE}:${SHORT_SHA}"
  - "${_IMAGE}:latest"
